pageextension 50118 "4HC Company Information" extends "Company Information"
{
    layout
    {
        addafter(Picture)
        {
            field("Report Footer"; Rec."Report Footer")
            {
                ApplicationArea = All;
                ToolTip = 'Specifies the footer text for reports generated by this company.';
                trigger OnValidate()
                begin
                    CurrPage.SaveRecord();
                end;
            }
        }
    }
}